### PR TITLE
updates HAMT

### PR DESCRIPTION
**Pull request by 97jaz**
The good news is that this version seems faster across the board in (optimize-level 3) builds. The bad news is that in default builds, large tables are faster, but small tables and generic iteration are slower.

Oh, also I still haven't written a decent test suite for this. I've basically been relying on hash-demo for that.

### CODE REVIEW

**Comment by 97jaz** [comment]
With #3, I can run the expander demo. Unfortunately, it doesn't work with this HAMT implementation. I found one very simple error in `cnode-index`. When I fixed that I got another, less obvious error:
```
write: cycle detected; proceeding with (print-graph #t)
make: *** [expander-demo] Error 255
```
So I'm going to track that down.

~~(Ugh, the control demo is also ridiculously slow with this implementation, so there's obviously something broken in this HAMT.)~~ (Turned out to be a different problem.)

**Comment by 97jaz** [comment]
I'm giving up on this for the night, but I found out that this problem seems to occur whenever the expander's `boot` procedure is used -- even in non-application position -- in `demo/expander.ss`. I reduced the whole file to:
```scheme
(import (expander)
        (io))

(define (show v) (write v) (newline))

boot
(show 3)
```
and the same error occurs. (Without the `boot` line, it writes 3, as you'd expect.) Same thing for `(procedure? boot)`, etc.

So it looks like when I use this hamt implementation, something seriously screwy is going on. I wonder if I have some residual code lying around that was built using the other hamt implementation, but I'm not sure what. I've done both a `make rktl` and `make clean`.

**Comment by 97jaz** [comment]
Yeah, so touching any export from `expander` results in that "cycle detected" error. From its description (specifically the fact that it comes from `write`), my guess is that it's an error that occurs when trying to write an error message from the real error. But that's only a guess, of course.

So, @mflatt, any ideas on either how a hamt implementation could cause this kind of error in the expander module or on debugging strategies?

(Oh, and the error *doesn't* occur when I touch exports from `io`, which is also required by the expander demo.)

**Comment by 97jaz** [comment]
If I load the file in an interactive repl, I can get some additional info:
```
> (load "demo/expander.ss")
write: cycle detected; proceeding with (print-graph #t)
> boot
cyclic dependency involving invocation of library (expander)
  context...:
   compile
   new-cafe
```
But the hamt impl doesn't `import` anything, so it's hard to see how it could affect the library dependencies.

**Comment by mflatt** [comment]
[Sorry – Yet again, GitHub notifications didn't reach me, so I didn't know that this PR was here.]

The "cycle detected" message is a warning that something can't print without turning on `print-graph`. Despite "proceeding" in the message, it doesn't proceed, likely because "core.so" mangles the exception handler to abort on warnings. It's downhill from there.

For now, you could add `(print-graph #t)` to your experiments to avoid the warning and fallout.

**Comment by 97jaz** [comment]
@mflatt The thing is, I'm not `write`-ing anything in my own experiments, and I can't tell where the attempt to `write` is coming from. I'm guessing that it's an attempt to display an error message.

But based on what you said, maybe I can mess around with the exception handler in `core` to get some more information out of this. That'll be my next approach. Thanks again.

**Comment by mflatt** [comment]
I've fixed exception handling to not abort on warnings. As you guessed, printing was part of forming an error message: "vector-ref: 2 is not a valid index ....".

**Comment by mflatt** [comment]
FWIW, the immediate bug is a `(fx1+ 1)` instead of `(fx1+ i)` on line 329. Something else goes wrong, though, so that the macro expander doesn't work – possibly a problem in `node-keys-subset?`.

**Comment by 97jaz** [comment]
@mflatt Thanks -- with your change to exception handling, I've been able to discover a few problems. (And you were right about the subset code, too.)

Edit -- I haven't pushed any of these changes yet, though.

**Comment by 97jaz** [comment]
@mflatt It's working now, and I've pushed my changes to this branch. Performance on the hash demo is more impressive than on the expander demo.

## hash demo
unoptimized build:
```
large tables
cpu time: 338 real time: 339 gc time: 7
cpu time: 370 real time: 370 gc time: 4
small tables
cpu time: 375 real time: 376 gc time: 0
safe iterate
cpu time: 225 real time: 225 gc time: 0
generic iterate
cpu time: 222 real time: 223 gc time: 0
unsafe iterate
cpu time: 20 real time: 20 gc time: 0
safe vs. unsafe on small table
cpu time: 124 real time: 125 gc time: 1
cpu time: 245 real time: 246 gc time: 0
mutable large tables
cpu time: 81 real time: 82 gc time: 0
mutable small tables
cpu time: 93 real time: 94 gc time: 4
mutable iterate
cpu time: 37 real time: 37 gc time: 0
mutable for-each
cpu time: 44 real time: 45 gc time: 0
mutable destructive for-each
cpu time: 104 real time: 104 gc time: 1
primitive mutable large tables
cpu time: 73 real time: 74 gc time: 0
primitive mutable small tables
cpu time: 77 real time: 78 gc time: 0
weak equal table
500
many tables
cpu time: 880 real time: 881 gc time: 379
148332704
```
optimized build:
```
large tables
cpu time: 171 real time: 171 gc time: 6
cpu time: 231 real time: 232 gc time: 4
small tables
cpu time: 211 real time: 211 gc time: 0
safe iterate
cpu time: 75 real time: 76 gc time: 0
generic iterate
cpu time: 76 real time: 77 gc time: 0
unsafe iterate
cpu time: 13 real time: 13 gc time: 0
safe vs. unsafe on small table
cpu time: 78 real time: 78 gc time: 1
cpu time: 181 real time: 181 gc time: 0
mutable large tables
cpu time: 79 real time: 80 gc time: 0
mutable small tables
cpu time: 91 real time: 92 gc time: 4
mutable iterate
cpu time: 31 real time: 31 gc time: 0
mutable for-each
cpu time: 33 real time: 33 gc time: 0
mutable destructive for-each
cpu time: 91 real time: 92 gc time: 1
primitive mutable large tables
cpu time: 72 real time: 72 gc time: 0
primitive mutable small tables
cpu time: 82 real time: 82 gc time: 0
weak equal table
500
many tables
cpu time: 700 real time: 701 gc time: 368
148502208
```
- The immutable table performance is not quite within a factor of 2 of the mutable tables. 
- Safe iteration benefits *a lot* from optimize level 3.

## Expander demo
cpu time of *unoptimized* build, averaged over 10 runs:
```
current master: 7.078823829400001
with updated hamt: 7.1105441884000005
```

cpu time of *optimized* build, averaged over 10 runs:
```
current master: 6.5695874449s
with updated hamt: 6.490648149499999
```
So a, uh, very modest improvement on optimized builds and a very modest loss on unoptimized builds.

**Comment by mflatt** [comment]
Merged - thanks!

**Pull request closed without merging**
